# 1.C++ 命名空间

假设这样一种情况，当一个班上有两个名叫 Zara 的学生时，为了明确区分它们，我们在使用名字之外，不得不使用一些额外的信息，比如他们的家庭住址，或者他们父母的名字等等。

同样的情况也出现在 C++ 应用程序中。例如，您可能会写一个名为 xyz() 的函数，在另一个可用的库中也存在一个相同的函数 xyz()。这样，编译器就无法判断您所使用的是哪一个 xyz() 函数。

因此，引入了**命名空间**这个概念，专门用于解决上面的问题，它可作为附加信息来区分不同库中相同名称的函数、类、变量等。使用了命名空间即定义了上下文。本质上，命名空间就是定义了一个范围。

我们举一个计算机系统中的例子，一个文件夹(目录)中可以包含多个文件夹，每个文件夹中不能有相同的文件名，但不同文件夹中的文件可以重名。

![namespace_eg](./assets/namespace_eg.jpg)

## 1.1 定义命名空间

命名空间的定义使用关键字 **namespace**，后跟命名空间的名称，如下所示：

```c++
namespace namespaceName{
    // 代码声明
}
```

为了调用带有命名空间的函数或变量，需要在前面加上命名空间的名称，如下所示：

```c++
name::code;// code是变量或者函数
```

命名空间如何为变量或函数等实体定义范围：

```c++
// 第一个命名空间
namespace first_space{
    void func(){
        cout<<"namespace is first_space"<<endl;
    }
}
// 第二个命名空间
namespace second_space{
    void func(){
        cout<<"namespace is second_space"<<endl;
    }
}

int main() {
    first_space::func();// 调用第一个命名空间中的函数
    second_space::func();// 调用第二个命名空间中的函数
    system("pause");
    return 0;
}
```



## 1.2 using指令

使用 **using namespace** 指令，这样在使用命名空间时就可以不用在前面加上命名空间的名称。这个指令会告诉编译器，后续的代码将使用指定的命名空间中的名称。(类似于一种声明)

```c++
// 第一个命名空间
namespace first_space{
    void func(){
        cout<<"namespace is first_space"<<endl;
    }
}
// 第二个命名空间
namespace second_space{
    void func(){
        cout<<"namespace is second_space"<<endl;
    }
}
using namespace first_space;

void test02(){
    func();// namespace is first_space
}

int main() {
    test02();
    system("pause");
    return 0;
}
```



+ using 指令也可以用来指定命名空间中的特定项目。例如，如果您只打算使用 std 命名空间中的 cout 部分，您可以使用如下的语句：

  ```c++
  using std::cout;
  ```

  随后的代码中，在使用 cout 时就可以不用加上命名空间名称作为前缀，但是 **std** 命名空间中的其他项目仍然需要加上命名空间名称作为前缀

+ **using** 指令引入的名称遵循正常的范围规则。**名称从使用 using 指令开始是可见的，直到该范围结束**。此时，**在范围以外定义的同名实体是隐藏的**。



## 1.3 不连续的namespace

**命名空间可以定义在几个不同的部分中**，因此命名空间是由几个单独定义的部分组成的。**一个命名空间的各个组成部分可以分散在多个文件中。**

所以，如果命名空间中的某个组成部分需要请求定义在另一个文件中的名称，则仍然需要声明该名称。下面的命名空间定义可以是定义一个新的命名空间，也可以是为已有的命名空间增加新的元素



## 1.4 嵌套的命名空间

+ 命名空间可以嵌套，可以在一个命名空间中定义另一个命名空间

  ```c++
  namespace first_space{
      void func(){
          cout<<"namespace is first_space"<<endl;
      }
      namespace  first_space_son{
          void func(){
              cout<<"namespace is first_space"<<endl;
          }
  
      }
  }
  ```

+ 可以通过使用 **::** 运算符来访问嵌套的命名空间中的成员：

  ```c++
  using namespace first_space;
  using namespace first_space::first_space_son;
  ```




# 2. C++ 异常处理

异常是程序在执行期间产生的问题。C++ 异常是指在程序运行时发生的特殊情况，比如尝试除以零的操作。

异常提供了一种转移程序控制权的方式。C++ 异常处理涉及到三个关键字：**try、catch、throw**。

- **throw:** 当问题出现时，程序会抛出一个异常。这是通过使用 **throw** 关键字来完成的。
- **catch:** 在您想要处理问题的地方，通过异常处理程序捕获异常。**catch** 关键字用于捕获异常。
- **try:** **try** 块中的代码标识将被激活的特定异常。它后面通常跟着一个或多个 catch 块。



+ 如果有一个块抛出一个异常，捕获异常的方法会使用 **try** 和 **catch** 关键字。try 块中放置可能抛出异常的代码，try 块中的代码被称为保护代码。

  ```c++
  try {
          // 保护代码
      }catch(ExceptionName e1){
          // catch 块
      }catch(ExceptionName e2){
          // catch 块
      }
  ```

+ 如果 **try** 块在不同的情境下会抛出不同的异常，这个时候可以尝试罗列多个 **catch** 语句，用于捕获不同类型的异常。

## 2.1 抛出异常

如果 **try** 块在不同的情境下会抛出不同的异常，这个时候可以尝试罗列多个 **catch** 语句，用于捕获不同类型的异常。

以下是尝试除以零时抛出异常的实例：

```c++
double division(int a, int b)
{
    if( b == 0 )
    {
        throw "Division by zero condition!";
    }
    return (a/b);
}
```



## 2.2 捕获异常

**catch** 块跟在 **try** 块后面，用于捕获异常。您可以指定想要捕捉的异常类型，这是由 catch 关键字后的括号内的异常声明决定的。

```c++
	try
{
   // 保护代码
}catch( ExceptionName e )
{
  // 处理 ExceptionName 异常的代码
}
```

上面的代码会捕获一个类型为 **ExceptionName** 的异常。如果您想让 catch 块能够处理 try 块抛出的任何类型的异常，则必须在异常声明的括号内使用省略号 ...，如下所示：

```c++
try
{
   // 保护代码
}catch(...)
{
  // 能处理任何异常的代码
}
```



示例:

```c++
using std::cout;
using std::endl;
using std::string;
using std::cerr;

double division(int a, int b)
{
    if( b == 0 )
    {
        throw "Division by zero condition!";
    }
    return (a/b);
}

void test01(){
    try {
        int a=1;
        int b=0;
        division(a,b);
        // 保护代码
    }catch(const char* msg){
        // catch 块 
        //由于我们抛出了一个类型为 const char* 的异常，因此，当捕获该异常时，我们必须在 catch 块中使用 const char*。当上面的代码被编译和执行时，它会产生下列结果：
        cerr<<msg<<endl;// Division by zero condition!
    }

};

int main() {
    test01();
    system("pause");
    return 0;
}
```



## 2.3 C++ 标准的异常

C++ 提供了一系列标准的异常，定义在 **<exception>** 中，我们可以在程序中使用这些标准的异常。它们是以父子类层次结构组织起来的，如下所示：

![exceptions_in_cpp](./assets/exceptions_in_cpp.png)!]

下表是对上面层次结构中出现的每个异常的说明：

| 异常                   | 描述                                                         |
| :--------------------- | :----------------------------------------------------------- |
| **std::exception**     | 该异常是所有标准 C++ 异常的父类。                            |
| std::bad_alloc         | 该异常可以通过 **new** 抛出。                                |
| std::bad_cast          | 该异常可以通过 **dynamic_cast** 抛出。                       |
| std::bad_typeid        | 该异常可以通过 **typeid** 抛出。                             |
| std::bad_exception     | 这在处理 C++ 程序中无法预期的异常时非常有用。                |
| **std::logic_error**   | 理论上可以通过读取代码来检测到的异常。                       |
| std::domain_error      | 当使用了一个无效的数学域时，会抛出该异常。                   |
| std::invalid_argument  | 当使用了无效的参数时，会抛出该异常。                         |
| std::length_error      | 当创建了太长的 std::string 时，会抛出该异常。                |
| std::out_of_range      | 该异常可以通过方法抛出，例如 std::vector 和 std::bitset<>::operator[]()。 |
| **std::runtime_error** | 理论上不可以通过读取代码来检测到的异常。                     |
| std::overflow_error    | 当发生数学上溢时，会抛出该异常。                             |
| std::range_error       | 当尝试存储超出范围的值时，会抛出该异常。                     |
| std::underflow_error   | 当发生数学下溢时，会抛出该异常。                             |



## 2.4 定义新的异常

可以通过继承和重载 **exception** 类来定义新的异常。下面的实例演示了如何使用 std::exception 类来实现自己的异常：

```c++
#include <iostream>
#include <exception>

using std::cout;
using std::endl;
using std::string;
using std::cerr;
using std::exception;

class MyException : public exception
{
public:
    const char * what () const throw ()
    {
        return "C++ Exception";
    }
};

void test01(){
    try
    {
        throw MyException();
    }
    catch(MyException& e)
    {
        cout << "MyException caught" << endl;
        cout << e.what() << endl;
    }
};

int main() {
    test01();
    system("pause");
    return 0;
}
```

+ 在这里，**what()** 是异常类提供的一个公共方法，它已被所有子异常类重载。这将返回异常产生的原因。